name: CI

on:
 pull_request:
  types: [opened, synchronize, reopened, labeled]

jobs:
  build_ubuntu:
    env: 
      JOB_NAME: build_ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Install python modules
      shell: bash
      run: |
        pip install boto3 distro PyGithub
        pip --version
        which pip
        python --version
        which python

    - name: Run python
      shell: bash
      run: echo -e "import distro\nprint(distro.linux_distribution(full_distribution_name=False))"|python

