name: CI

on:
 pull_request:
  types: [opened, synchronize, reopened, labeled]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: set output
      run: echo "::set-output name=action_vehicle::spaceship"
    - name: Run a multi-line script
      run: |
        echo Add other actions to build, and another one,
        echo test, and deploy your project.
        echo "::set-output name=action_fruit::strawberry"
