name: CI

on:
 pull_request:
  types: [opened, synchronize, reopened, labeled]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Hello world action step
      uses: ./hello-world-javascript-action # Uses an action in the root directory
      id: hello
      with:
        who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
    - name: set output
      run: echo "::set-output name=action_vehicle::spaceship"
    - name: Publish build action
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: python ${GITHUB_WORKSPACE}/test-upload.py
    - name: Run a multi-line script
      run: |
        echo Add other actions to build, and another one,
        echo test, and deploy your project.
        echo "::set-output name=action_fruit::strawberry"
